/** Research areas offered during onboarding. They become the person's research interests. */
export const RESEARCH_DOMAINS = [
  "AI Hallucination",
  "AI Injection",
  "AI-Assisted Coding",
  "Additive Manufacturing (3D Printing)",
  "Agriculture and Precision Farming",
  "Analytical Intelligence and Machine Learning",
  "Applied Mathematics and Modeling",
  "Astrophysics and Cosmology",
  "Augmented and Virtual Reality",
  "Autonomous Vehicles and Drones",
  "Behavioral Economics",
  "Big Data Mining",
  "Bioinformatics and Systems Biology",
  "Biomedical Engineering",
  "Biometrics",
  "Biomimicry and Bio-inspired Design",
  "Blockchain",
  "Brain-Computer Interfaces (BCI)",
  "Climate Change and Environmental Modeling",
  "Cloud Computing and Virtualization",
  "Cognitive Computing",
  "Computational Linguistics",
  "Computer Vision",
  "Conversational AI and Chatbot",
  "Cryptography and Network Security",
  "Cybersecurity and Crypto",
  "Cybersecurity and Privacy",
  "Data Science and Statistics",
  "Deep Learning",
  "DevSecOps and Automated Engineering",
  "Digital Humanities",
  "E-commerce and Digital Marketing",
  "Edge AI",
  "Edge Computing",
  "Embedded Systems and VLSI",
  "Epidemiology and Public Health",
  "Ethics of Technology",
  "Explainable AI (XAI)",
  "Financial Technology (FinTech)",
  "Fluid Dynamics and Heat Transfer",
  "Game Development and Design",
  "Gen AI",
  "Genomics and Biotechnology",
  "Geoinformatics and Remote Sensing",
  "Health Information",
  "High-Performance Computing (HPC)",
  "Human Computer Interaction",
  "ILP",
  "Internet of Things",
  "LLM",
  "Mixed Reality (MR)",
  "Mobile and Web App",
  "Multi-Agent Systems",
  "NLP",
  "Nanotechnology and Advanced Materials",
  "Neuromorphic Computing",
  "Neuroscience",
  "Operations Research and Supply Chain",
  "Pharmacology and Oncology",
  "Power Systems and Smart Grids",
  "Precision Medicine",
  "Privacy-Preserving Machine Learning",
  "Prompt Engineering and Optimization",
  "Quantum Computing",
  "Reinforcement Learning",
  "Robotics and Autonomous Systems",
  "Sociology and Urban Planning",
  "Software Engineering and DevOps",
  "Space Systems Engineering",
  "Statistical Thermodynamics",
  "Structural Engineering and Materials",
  "Sustainable Energy and Cleantech",
  "Synthetic Biology",
  "Telecommunications and 5G/6G Networks",
  "Water Resources Engineering"
];
